config/routes.rb
Rails.application.routes.draw do
  
  resources :questions, :answers
  root 'questions#index'
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers,
    :reject_if => lambda { |a| a[:description].blank? },
    :allow_destroy => true

  validates :description, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.includes(:answers).page(params[:page]).per(5)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:description, answers_attributes: [:id, :description, :_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Questapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'nested_form', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #83C340;">

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= nested_form_for(@question) do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

  <ul>
    <% @question.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<p>
<%= f.label :description, "Add Question" %><br />
  <%= f.text_area :description, :cols => 80, :rows => 10 %>
</p>
<ol class="answers-field">
  <%= f.fields_for :answers do |builder| %>
  <li>
    <%= builder.text_field :description %>
    <%= builder.link_to_remove "Remove" %>
  </li>
</ol>
<% end %>

<p><%= f.link_to_add "Add Answer", :answers %></p>
<p><%= f.submit "Submit" %></p>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>


<div>
<ol>  
  <% @questions.each do |question| %>
    <li class="question-text"><%= question.description %></li>
    <h4>Options: </h4>
    <ol>
      <% question.answers.each do |answer| %>
        <li><%= answer.description %></li>
      <% end %>
    </ol>
    <br/>
    <span><%= link_to 'Edit', edit_question_path(question) %></span>
    <span><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    <hr/>
  <% end %>
</ol>
<%= paginate @questions %>
<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>